#!/bin/bash
#   Rollout - Dotfile Automation Script
#   Dynamically symlinks all files and directories in
#   dots/ folder (overwriting any files that exist)

#Variables/Constants

REPO=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd );
PREFIX=".";
DOTDIR=$REPO/dots;
DOTS=$(ls $DOTDIR);
filecount=0;
linkcount=0;
dircount=0;


for dot in $DOTS
do
    dest=$HOME/$PREFIX$dot;
    if [ -f $dest ]
    then
       echo "$dot: Overwriting."; 
       rm -f $dest;
       let "filecount+=1";
    elif [ -L $dest ]
    then
       echo "$dot: Overwriting."; 
       rm -f $dest;
       let "linkcount+=1";
    elif [ -d $dest ]
    then
       echo "$dot: Overwriting."; 
       rm -Rf $dest/;
       let "dircount+=1";
    fi

    if ln -s $DOTDIR/$dot $dest; then
        echo "$dot: Successfully Linked";
    else
        echo "$dot: Linking Failed";
    fi
done
echo -e "-------\nOverwritten: $filecount files - $linkcount links - $dircount dirs";
